### ISSUE TITLE
Update website Former::config to Former::setOption

### ISSUE THREAD

**Issue by jp7carlos** [Anahkiasen/former#424]
The website is a little outdated, there is no mention to how to set current bootstrap as default framework, which I found out is:

    Former::framework('TwitterBootstrap3');

Also it mentions Former::config. Which browsing the source code i think should be Former::setOption

**Comment by claar** [comment]
@jp7carlos Yes, sorry, improved documentation is a long-standing need of this project.

You can contribute fixes to the website at https://github.com/Anahkiasen/former/tree/gh-pages, or edit the wiki at https://github.com/Anahkiasen/former/wiki
