### ISSUE TITLE
Noobs Question

### ISSUE THREAD

**Issue by t0n1zz** [Anahkiasen/former#426]
Hi, i just trying your package and very excited with live validation feature(i still don't understand about any other features)

but it's just there is many things that missed from your documentation like:

1. former::open() is used to open the form, so how to integrate route inside it? i tried former::open()->route('article.create'); but not working

2. what i like about blade form helper in laravel is i don't need to control how the field value appear when i call update form, i just do {{ form::text('name') }} and it will automatically show the right value for 'name' field from database/eloquent models, how to do that in former?

3. how can i figured out all avaiable class for former? like former::open() , i don't get any autocompletion from phpstorm..

**Comment by t0n1zz** [comment]
@tmayr 
1. can you give me a working simple example on implementing that? since i tried but can't make it works
2. where should i put ->populate($model)? put it with former::open()

**Comment by claar** [comment]
@t0n1zz As long as you put `->populate()` before you output the field you want to populate, it should work. An example:

```php
<?php
  $model = Client::find(2);
  Former::populate($model);
?>
<?= Former::horizontal_open('myform')->route('login'); ?>
<?= Former::text('name') ?>
<?= Former::actions( Former::primary_submit('Submit'), Former::default_reset('Reset') ) ?>
<?= Former::close() ?>
```
