### ISSUE TITLE
Checkbox is always checked

### ISSUE THREAD

**Issue by eComEvo** [Anahkiasen/former#427]
Doing both of the following always results in the checkbox being checked in both cases:
{{ Former::checkbox($val['name'], '')->text($val['display_name']) }}
{{ Former::checkbox($val['name'], '')->text($val['display_name'])->check() }}

The value passed in the form is "off" or "on".

How do I make the checkbox unchecked?

**Comment by claar** [comment]
Checkboxes in Former can be a bit finicky currently, sorry.

The most reliable way to uncheck a checkbox is to populate it with null, rather than "off".

**Comment by eComEvo** [comment]
That did it! Thanks! Been pulling my hair out trying to figure what I was doing wrong. :)
