### ISSUE TITLE
Mixed form element orientation.

### ISSUE THREAD

**Issue by bschooly** [Anahkiasen/former#430]
I'm using vertical form layout but I need to also lay out certain elements horizontally. I saw this:

Former::group('Metadata')
  Former::text('key')
  Former::text('value')
Former::closeGroup()

mentioned elsewhere but I can't get that to work. The Key and Value fields are vertical as well. What am I missing?

Bill

**Comment by claar** [comment]
@bschooly I'm not sure exactly what you're wanting,  but I usually just revert to HTML + Former::raw() when I need to do things that Former doesn't support out of the box:

```php
{{ Former::vertical_open('my_form') }}
{{ Former::textarea('field1'); }}
<div class="form-group inline-group">
  <label class="control-label col-sm-2">Name</label>
  <div class="col-sm-5">
    <div class="form-group">
      {{ Former::text('first_name')->placeholder('First Name')->raw() }}
    </div>
  </div>
  <div class="col-sm-5">
    <div class="form-group">
      {{ Former::text('last_name')->placeholder('Last Name')->raw() }}
    </div>
  </div>
</div>
{{ Former::close() }}
```

**Comment by bschooly** [comment]
To be clear: I want:

label1
field1
label2
field2
label3 
field3 field4
label5
field5
....

Is that possible?

**Comment by claar** [comment]
@bschooly The code in my comment above is close to what you need for "field3 field4". Former itself can't help you with this, unfortunately.

**Comment by bschooly** [comment]
Thanks for the quick replies. One last one for you. How do you hide a field? I hid with something like this:

{{ FORM::BxField('ccnum', 'Credit Card Number', true, false)->addClass("cc") }}

BxField is just a macro for Field::. Whenever I do this only the text field is hidden. The label remains. Can I do this with Former or is raw required for this as well?

Bill

**Comment by claar** [comment]
Sorry, I'm not following your question.

**Comment by bschooly** [comment]
In the above, note the use of the "cc" class. In javascript I set style for this class to 'display:none;' When I do this only the text field is hidden; the associated label is not.
Bill

**Comment by claar** [comment]
Ahhh... yes, in Former, you can use `Former::text('ccnum')->addClass('cc')`

**Comment by bschooly** [comment]
Yep. But when I do css on the class to hide it,  I don't get BOTH the field and label hidden. Only the field :(

**Comment by claar** [comment]
@bschooly Ah, I finally understand. You're saying you already tried `Former::addClass`, but it is applying the 'cc' CSS class to the input rather than the entire form-group. Why didn't you say so :)

Try `Former::text('ccnum')->onGroupAddClass('cc')`

**Comment by bschooly** [comment]
Thanks. That worked.
