### ISSUE TITLE
Live validation use with twitter animated "Loading..."

### ISSUE THREAD

**Issue by bschooly** [Anahkiasen/former#432]
I'm using:

$(document).ready(function(){
    
    // Our busy cursor
    $("[data-loading-text]").on('click', function () {
        var $btn = $(this).button('loading')
    // business logic...
    //$btn.button('reset')
    });
    
});

to animate/change the Save (or other_ button once the button is pressed. The problem I have is when live validation catches errors my button is left in the "Loading....." state. How do I avoid this?

The button html looks like:

<input id="login" type="submit" name="login" value="Login" class="btn btn-primary" data-loading-text="Loading..." autocomplete="off">

Bill

**Comment by claar** [comment]
@bschooly Unless you can show that this problem is caused by Former doing something unexpected, I'm afraid this issue queue isn't the right place to diagnose your issue -- it appears to be purely a JavaScript matter to me, while Former is a PHP library.
