### ISSUE TITLE
Laravel 5 - Exception

### ISSUE THREAD

**Issue by TheTechnoMan** [Anahkiasen/former#439]
Hey,

when I set the Framework to TwitterBootstrap3 I get:

ErrorException in TwitterBootstrap3.php line 192: Invalid argument supplied for foreach() (View: C:\xampp\htdocs\XXX\Modules\XXX\Resources\views\cp\admin\products\add.blade.php)

The normal TwitterBootstrap works fine but does of course not create the correct markup.

Thanks!

**Comment by barryvdh** [comment]
I get this too.

**Comment by barryvdh** [comment]
Does #440 fix it for you?

**Comment by barryvdh** [comment]
Or as a workaround, copy `config/former.php` to your local config, but also copy `config/TwitterBootstrap3.php` to your local `config/former.TwitterBootstrap3.php`

**Comment by claar** [comment]
#440 has been committed -- this should be fixed on the 4.0 branch. Note that you must specify the framework in the config file currently until a proper fix for dynamically selecting the framework lands.
