### ISSUE TITLE
Class 'Illuminate\Config\FileLoader' not found

### ISSUE THREAD

**Issue by gilbitron** [Anahkiasen/former#443]
Getting this error when trying to use Former outside of Laravel.

**Comment by gilbitron** [comment]
Looks like FileLoader was removed in the latest version of illuminate/config (5.0+), but because you have used `>=4.2` in composer.json it loads v5.0+. Should probably be `~4.2`.

**Comment by claar** [comment]
Hey @gilbitron, please use the 4.0 branch for Laravel 5.

I've updated composer.json to be ~4.2, thanks,
